apiVersion: v1
kind: ConfigMap
metadata:
  name: openblog-js-nginx-config
  namespace: openblog-js
data:
  default.conf: |
    server {
      listen      80;
      listen [::]:80;
      server_name localhost;

      root        /opt/openblog-js;
      index       index.html index.htm index.php;

      location /_next/ {
          root /opt/openblog-js;
      }

      location /static/ {
          root /opt/openblog-js;
      }

      location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf|webp)$ {
          root /opt/openblog-js;
          access_log off;
          expires 1d;
          add_header Cache-Control "public, immutable";
      }

      error_log   /var/log/nginx/error.log warn;
      access_log  /var/log/nginx/access.log main;
    }