apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: openblog-js-backend-autoscaling
  namespace: openblog-js
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openblog-js-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: openblog-js-frontend-autoscaling
  namespace: openblog-js
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openblog-js-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50