apiVersion: v1
kind: PersistentVolume
metadata:
  name: openblog-js-postgres-pv
  namespace: openblog-js
spec:
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/openblog-js-postgres-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-node