apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openblog-js-postgres-pvc
spec:
  accessmodes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: openblog-js-postgres-pv