apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openblog-js-postgres-pvc
  namespace: openblog-js
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: openblog-js-postgres-pv