apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openblog-js-postgres
  namespace: openblog-js
  labels:
    app: openblog-js-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openblog-js-postgres
  template:
    metadata:
      labels:
        app: openblog-js-postgres
    spec:
      containers:
        - name: openblog-js-postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openblog-js-postgres-master-secret
                  key: password
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: openblog-js-postgres-pvc