name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      #Setting Modules
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "22"

    
      #Setting Environment Variables
      - name: Set Backend Version
        run: echo "BACKEND_VERSION=$(grep iagouvea/openblog-js-backend ./k8s/deployment.yaml | awk -F ':' '{print $3}')" >> $GITHUB_ENV
      
      - name: Set Frontend Version
        run: echo "FRONTEND_VERSION=$(grep iagouvea/openblog-js-frontend ./k8s/deployment.yaml | cut -d: -f2)" >> $GITHUB_ENV


      #Backend Workflow
      - name: Install Dependences (Backend)
        run: npm install
        working-directory: ./backend

      - name: Build Docker Image (Backend)
        run: docker build . --file Dockerfile --tag iagouvea/openblog-js-backend:${BACKEND_VERSION}
        working-directory: ./backend

      - name: Send Docker image to repository (Backend)
        run: docker push iagouvea/openblog-js-backend:${BACKEND_VERSION}


      #Frontend Workflow
      - name: Install Dependences (Frontend)
        run: npm install
        working-directory: ./frontend

      - name: Build Frontend (Frontend)
        run: npm run build
        working-directory: ./frontend

      - name: Build the Docker image (Frontend)
        run: docker build . --file Dockerfile --tag iagouvea/openblog-js-frontend:${FRONTEND_VERSION}
        working-directory: ./frontend

      - name: Send Docker image to repository (Frontend)
        run: docker push iagouvea/openblog-js-frontend:${FRONTEND_VERSION}


      #Update Deployment
      #- name: Overwrite image version in Deployment.yaml (Backend/Frontend)
      #  run: |
      #    sed -i "s|image: iagouvea/openblog-js-backend:.*|image: iagouvea/openblog-js-backend:${IMAGE_TAG}|g" k8s/deployment.yaml
      #    sed -i "s|image: iagouvea/openblog-js-frontend:.*|image: iagouvea/openblog-js-frontend:${IMAGE_TAG}|g" k8s/deployment.yaml
      #    git config user.name "github-actions"
      #    git config user.email "actions@github.com"
      #    git commit -am "Atualiza imagem para tag ${IMAGE_TAG}"
      #    git push

